server {
    listen 80;
    
    # Le dossier où Nginx trouve le build de ton React
    root /usr/share/nginx/html;
    index index.html;

    # La magie pour que React Router gère les URLs comme /dashboard
    location / {
        try_files $uri $uri/ /index.html;
    }
}