name: Backend CI

on:
  push:
    branches: [ "main" ] # Se lance quand tu push sur main
  pull_request:
    branches: [ "main" ]

jobs:
  build-java:
    runs-on: ubuntu-latest # GitHub nous prête un serveur Ubuntu

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation du JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build avec Maven (sans tests pour l'instant)
        run: |
          cd easybee-backend
          mvn clean compile